version: "3"

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: client
    ports: 
      - 3000:3000
    volumes:
      - ./client:/app
    depends_on: 
      - server
  server:
    build:
        context: ./server
        dockerfile: Dockerfile.dev
    container_name: server
    restart: always
    environment:
      NODE_ENV: DEV
    volumes:
      - ./server:/app
    ports:
      - 4000:4000
    depends_on: 
      - database
  database:
    image: postgres:12.7
    container_name: database
    restart: always
    environment:
      POSTGRES_USER: OTOT-B-USER
      POSTGRES_PASSWORD: OTOT-B-PW
      POSTGRES_DB: OTOT-B
    volumes:
      - ./server/migrations:/docker-entrypoint-initdb.d/
      - db-data:/var/lib/postgresql/data
    ports:
      - 5433:5432

volumes:
  db-data: