version: "3"

services:
  server:
    build:
        context: ./server
        dockerfile: Dockerfile
    container_name: server
    restart: always
    environment:
      DB_CONNECTION_STRING: postgres://OTOT-B-USER:OTOT-B-PW@host.docker.internal:5433/OTOT-B
    volumes:
      - ./server:/app
      - server-mods:/app/node_modules
    ports:
      - 4000:4000
  database:
    image: postgres:12.7
    container_name: database
    restart: always
    environment:
      POSTGRES_USER: OTOT-B-USER
      POSTGRES_PASSWORD: OTOT-B-PW
      POSTGRES_DB: OTOT-B
    volumes:
      - ./server/migrations:/docker-entrypoint-initdb.d/
      - db-data:/var/lib/postgresql/data
    ports:
      - 5433:5432

volumes:
  server-mods:
  db-data: