version: "3"
services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: server
    ports:
      - 4000:4000
    volumes:
      - ./server/:/usr/app/
  cache:
    image: redis
    container_name: cache
    ports:
    - "6379:6379"