# app.yaml

runtime: nodejs14

beta_settings:
  # The connection name of your instance, available by using
  # 'gcloud beta sql instances describe [INSTANCE_NAME]' or from
  # the Instance details page in the Google Cloud Platform Console.
  cloud_sql_instances: cs3219-otot-324906:asia-southeast1:cs3219-otot-b-db-prod
